### ISSUE TITLE
Oui-field property is undefined

### ISSUE THREAD

**Issue by marie-j** [ovh/ovh-ui-kit#496]
### Description

When using a `oui-field` out of a `form` with a nested model, a property is undefined error 

### Steps to reproduce

1. Create a oui-field out of a `form` element
2. Add an input with a model being `model.nestedProperty`
3. Try to edit the model

**Expected behavior**:

The model should be updated

**Actual behavior**:

The model gets updated but an error appears "Cannot read property 'nestedProperty' of undefined"

**Frequency**:
Always

**Comment by FredericEspiau** [comment]
````
Actual behavior:

The model gets updated but
````

But what ? The suspens is killing me !
