### ISSUE TITLE
[oui-flag]: background-image url

### ISSUE THREAD

**Issue by antleblanc** [ovh/ovh-ui-kit#593]
### Steps to reproduce

1. Visit: https://unpkg.com/@ovh-ux/ui-kit@4.0.4/dist/css/oui.css
2. Search `export default`
2. See errors

**Expected behavior**:

A valid URL should be specified.

**Actual behavior**:

A wrong URL is defined probably due to an Issue when compiling the styles.

**Frequency**:

Always.

### Additional information

Our current [shared webpack configuration](https://github.com/ovh/manager/blob/master/packages/manager/tools/webpack-config/README.md) is not able to build a package that rely on this version ([v4.0.4](https://github.com/ovh/ovh-ui-kit/releases/tag/v4.0.4)).

**Comment by AxelPeter** [comment]
Has been fixed with in this release: https://github.com/ovh/ovh-ui-kit/blob/master/packages/libs/ui-kit/CHANGELOG.md#405-2020-03-26
