### ISSUE TITLE
[oui-collapsible] issue with overflow on popovers

### ISSUE THREAD

**Issue by jperchoc** [ovh/ovh-ui-kit#773]
### Description

Using `popover` inside a `oui-collapsible` does not work well due to overflow:

![image](https://user-images.githubusercontent.com/24541481/157672412-aec6dc39-0ed6-4ebe-8c39-9025c1a0fbb5.png)

### Steps to reproduce

1. Create a `oui-collapsible` element
2. Add a `oui-field` with a `label-popover`

**Expected behavior**:

The popover overflow should be visible:

![image](https://user-images.githubusercontent.com/24541481/157672526-104a2ae7-b43e-4b78-922b-c80f08f1f6ef.png)

**Frequency**:
5 (always)

### Additional information
Workaround used: 

```
oui-collapsible {
    .oui-collapsible__header[aria-expanded='true'] ~ .oui-collapsible__wrapper {
      overflow: visible;
    }
}
```

**Comment by JacquesLarique** [comment]
The suggested fix has been applied, it's now working as expected.

**Comment by JacquesLarique** [comment]
The suggested fix has been applied, it's now working as expected.
