### ISSUE TITLE
[oui-numeric] Default behavior on Firefox

### ISSUE THREAD

**Issue by jperchoc** [ovh/ovh-ui-kit#786]
### Description

With Firefox, the oui-numeric still has the up and down arrows which is the default behavior of numeric inputs. This leads to incorrect display on small numeric values.

### Steps to reproduce

```
<oui-field
    data-label="{{:: 'data_processing_submit_job_stepper_spark_driver_cores_label' | translate }}"
>
    <div class="sizing__advanced-units-container">
        <oui-numeric
            name="driver-cores"
            data-model="$ctrl.state.driverCores"
            data-min="$ctrl.jobParameters.driver_cores.validator.min"
            data-max="$ctrl.jobParameters.driver_cores.validator.max"
        >
        </oui-numeric>
    </div>
    <span class="sizing__advanced-units">vCores</span>
</oui-field>
```

**Expected behavior**:

Arrows should not appear / hide value (screenshot on Linux OS)
![image](https://user-images.githubusercontent.com/24541481/177724633-7f03b922-7024-4857-b337-14c46685e04c.png)

**Actual behavior**:
Default behavior truncates input value (Windows OS - Firefox)
![image](https://user-images.githubusercontent.com/24541481/177723745-49b00e39-0110-416f-b6f9-1a93d328bf3b.png)

**Frequency**:
5 (always)

**Comment by baaastijn** [comment]
this issue is clearly a major one

**Comment by jperchoc** [comment]
Issue is also appearing on Mac OS with Firefox 104 
![image](https://user-images.githubusercontent.com/24541481/190598507-b1c113eb-ba46-4e6a-8c3e-d66c26a413ef.png)
